#!/bin/sh
### BEGIN INIT INFO
# Provides:          hommyd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Create dynamic part of /etc/hommyd
# Description:       /etc/hommyd is a hommy deamon. 
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
. /lib/lsb/init-functions
JS_FILE=/home/pi/git/node-projects/hommy/hommy.js
PID=/var/run/hommy.pid
LOG_FILE=/var/log/hommy.log
. /lib/lsb/init-functions

export DEBUG=*,-l2cap-ble

do_start () {
	# Start proxy and hommy as deamons
	echo starting hommy deamon $JS_FILE
        if [ -f $PID ]; then
          do_stop;
        fi
	nohup node $JS_FILE 2>&1 > $LOG_FILE &
	log_end_msg $?
	echo $! > $PID
}

do_stop () {
	echo stopping hommy daemon
	kill -KILL $(cat $PID)
	log_end_msg $?
	rm $PID
}

do_status () {
	ps -AeLf | grep $(cat $PID)
	log_end_msg $?
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: hommyd [start|stop|status]" >&2
	exit 3
	;;
esac

:
