#!/bin/sh
### BEGIN INIT INFO
# Provides:          nexod
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Create dynamic part of /etc/nexod
# Description:       /etc/nexod is a nexo-proxy deamon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
JS_FILE=/home/pi/git/node-projects/nexo_proxy/proxy.js
PID=/var/run/nexo-proxy.pid
LOG_FILE=/var/log/nexo_proxy.log
. /lib/lsb/init-functions

export DEBUG=proxy,client

do_start () {
	# Start proxy and hommy as deamons
	echo starting nexo-proxy deamon $JS_FILE
	if [ -f $PID ]; then
	  do_stop;
	fi
	nohup node $JS_FILE 2>&1 > $LOG_FILE &
        log_end_msg $?
        echo $! > $PID
	sleep 5
}

do_stop () {
	echo stopping daemons
	kill -KILL $(cat $PID)
	log_end_msg $?
	rm $PID
}

do_status () {
	ps -Al | grep $(cat $PID)
	log_end_msg $?
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: nexod [start|stop|status]" >&2
	exit 3
	;;
esac

:
