#!/bin/sh
### BEGIN INIT INFO
# Provides:          nexod
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:	     0 1 6
# Short-Description: Create dynamic part of /etc/nexod
# Description:       /etc/nexod is a nexo-proxy deamon.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
. /lib/lsb/init-functions

export DEBUG=proxy

do_start () {
	# Start proxy and hommy as deamons
	echo starting nexo-proxy deamon
#	rm /var/log/nexo-proxy.forever.log
#	rm /var/log/nexo-proxy.out
#	rm /var/log/nexo-proxy.err
	forever start -p /var/run/hommy/ -c /usr/local/bin/node --uid "nexo-proxy" -a \
		-l /var/log/nexo-proxy.forever.log \
		-o /var/log/nexo-proxy.out \
		-e /var/log/nexo-proxy.err \
		--sourceDir /home/pi/git/node-projects/nexo_proxy/ proxy.js
	log_end_msg $?
	sleep 5
}

do_stop () {
	echo stopping daemons
	forever stop /home/pi/git/node-projects/nexo_proxy/proxy.js
	log_end_msg $?
}

do_status () {
	forever list | grep nexo-proxy
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	do_stop
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: nexod [start|stop|status]" >&2
	exit 3
	;;
esac

:
